name: miniquad_ios_example
options:
  bundleIdPrefix: com.rust
configs:
  Debug: debug
  Release: release
targets:
  cargo_ios:
    type: ""
    platform: iOS
    legacy:
      toolPath: /bin/sh
      arguments: "build_rust_deps.sh"
      workingDirectory: "."
  miniquad_game:
    sources: src
    type: application
    platform: iOS
    deploymentTarget: "12.0"
    sources: src/
    scheme:
      environmentVariables:
        - variable: RUST_BACKTRACE
          value: 1
          isEnabled: true
        - variable: RUST_LOG
          value: info
          isEnabled: true
    settings:
      base:
        HEADER_SEARCH_PATHS: ["$(inherited)", "src/"]
        OTHER_LDFLAGS: ["$(inherited)", "-lminiquad_ios_example"]
        ENABLE_BITCODE: NO
        CLANG_CXX_LANGUAGE_STANDARD: c++11
        CLANG_CXX_LIBRARY: libc++
      configs:
        debug:
          "LIBRARY_SEARCH_PATHS[sdk=iphoneos*][arch=arm64]":
            - $(inherited)
            - "../target/aarch64-apple-ios/debug"
          "LIBRARY_SEARCH_PATHS[sdk=iphonesimulator*][arch=arm64]":
            - $(inherited)
            - "../target/aarch64-apple-ios-sim/debug"
          "LIBRARY_SEARCH_PATHS[sdk=iphonesimulator*][arch=x86_64]":
            - $(inherited)
            - "../target/x86_64-apple-ios/debug"
        release:
          "LIBRARY_SEARCH_PATHS[sdk=iphoneos*][arch=arm64]":
            - $(inherited)
            - "../target/aarch64-apple-ios/release"
          "LIBRARY_SEARCH_PATHS[sdk=iphonesimulator*][arch=arm64]":
            - $(inherited)
            - "../target/aarch64-apple-ios-sim/release"
          "LIBRARY_SEARCH_PATHS[sdk=iphonesimulator*][arch=x86_64]":
            - $(inherited)
            - "../target/x86_64-apple-ios/release"
    dependencies:
      - sdk: OpenGLES.framework
      - sdk: GLKit.framework
      - sdk: Security.framework
      - sdk: UIKit.framework
      - target: cargo_ios
        embed: false
    info:
      path: src/Info.plist
      properties:
        UILaunchStoryboardName: LaunchScreen
